# Generated by Django 3.0.2 on 2021-01-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('birthdate', models.DateField()),
                ('phone', models.IntegerField()),
            ],
            options={
                'db_table': 'Login_users',
            },
        ),
    ]
