# Generated by Django 3.0.2 on 2021-01-20 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_login_user_username'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='login_user',
            table='Users',
        ),
    ]
